server:
  port: 8687
  jetty:
    threads:
      acceptors: 2 # 接收连接的线程数
      selectors: 4 # 处理连接的线程数
      max: 20 # 最大的线程数
      min: 4 # 最小的线程数
    max-http-form-post-size: 1000000B # 最大的 HTTP POST 大小，0 表示无限制
spring:
  application:
    name: ogumaproject
  datasource:
    druid:
      db-type: oracle
      # JDBC请换成自己本地的属性↓↓↓
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@//52.199.163.241:1521/FREEPDB1
      username: JPTCRSDBA1
      password: JPTCRSDBA1
      # JDBC请换成自己本地的属性↑↑↑
      max-active: 30
      max-wait: 1500000
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  configuration:
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jp.co.ogumaproject.ppok.entity